version: '3.3'

services:
  docker-cron:
    build:
      context: ./docker_cron
      dockerfile: Dockerfile
    container_name: docker-cron
    volumes:
      - type: bind
        source: ../pgsql-backups
        target: /var/pgsql-backups
      - type: bind
        source: ../fs-backups
        target: /var/fs-backups
      - type: bind
        source: ./suncity-hrm-deployer
        target: /var/deployer
    env_file:
      - ./docker_cron.env
    environment:
      - DB_USER=suncity
      - DB_PASS=wearetheword
      - DB_NAME=suncity
      - DB_HOST=postgres-master
      - DB_PORT=5432
    networks:
      - suncity

networks:
  suncity:
