version: '3.3'

services:

  seaweedfs_master:
    image: visionpsn/seaweedfs
    container_name: seaweedfs_master
    ports:
      - 9333:9333
    command: "master"
    networks:
      - suncity

  seaweedfs_volume:
    image: visionpsn/seaweedfs
    container_name: seaweedfs_volume
    ports:
      - 8080:8080
    volumes:
      - ../fs_data:/data
    command: 'volume -max=5 -mserver="seaweedfs_master:9333" -port=8080'
    depends_on:
      - seaweedfs_master
    networks:
      - suncity

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - suncity

  memcached:
    image: memcached
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - suncity

  postgres-master:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres-master
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      - DB_USER=suncity
      - DB_PASS=wearetheword
      - DB_NAME=suncity
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=replpass
    networks:
      - suncity


  postgres-slave-01:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres-slave-01
    ports:
      - 5433:5432
    volumes:
      - ./db_data_bak:/var/lib/postgresql
    environment:
      - REPLICATION_MODE=slave
      - REPLICATION_SSLMODE=prefer
      - REPLICATION_HOST=postgres-master
      - REPLICATION_PORT=5432
      - REPLICATION_USER=repluser
      - REPLICATION_PASS=replpass
    networks:
      - suncity

  docker-cron:
    build:
      - context: ./docker_cron
      - dockerfile: Dockerfile
    container_name: docker-cron
    volumes:
        - ./cron.log:/var/log/cron.log
    environment:
      - DB_USER=suncity
      - DB_PASS=wearetheword
      - DB_NAME=suncity
      - DB_HOST=postgres-master
      - DB_PORT=5432
    networks:
      - suncity

networks:
  suncity:
